- name: Configure firewall and install Apache2
  hosts: webworkers

  vars_files:
  - vars/conf.yml

  tasks:
    # Corresponding with tasks described in https://www.linode.com/docs/security/securing-your-server/
 	- name: configure iptables
      template: src=files/iptables.firewall.rules dest=/etc/iptables.firewall.rules
      notify:
        - reload iptables

    - name: install fail2ban
      yum: name={{ item }} state=latest
      with_items:
        - fail2ban

    - name: install epel
      yum: name={{ item }} state=latest
      with_items:
        - epel-release

    # Installs apache2 and disables the default site

    - name: install httpd
      yum: name={{ item }} state=latest
      with_items:
        - httpd

    - name: remove default apache2 site
      command: a2disssite *default
      args:
        # informs ansible of the expected side effects as a means of determining 'change'
        removes: /etc/apache2/sites-enabled/*default.conf
      notify:
        - restart httpd

  handlers:

    # The order of handlers here represents the order in which they are executed so we ensure ssh is last to ensure that
    # authentication changes only take at the end of the run.

    - name: reload iptables
      action: shell /sbin/iptables-restore < /etc/iptables.firewall.rules

    - name: restart httpd
      service: name=httpd state=restarted
